[package]
name = "game"
version = "0.1.0"
edition = "2024"

[dependencies]
minifb = "0.27"
serde = { version = "1.0", features = ["derive"] }
ron = "0.8"
zip = "0.6"
anyhow = "1.0"
quick-xml = "0.38.4"
